// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CRUD.Models;

public partial class student
{
    public string First_Name { get; set; }

    public string Last_Name { get; set; }

    public string Address { get; set; }

    public string Email { get; set; }

    public int? age { get; set; }

    public int? Dept_id { get; set; }

    public int id { get; set; }

    public virtual Department Dept { get; set; }
}